#!/usr/bin/env python3

import json
import locale
import sys
from reportlab.platypus import SimpleDocTemplate,Paragraph, Table
import emails
import os

user = os.environ.get('USER')
path = "/home/" + user
pdf_path = "/tmp/cars.pdf"

def load_data(filename):
  """Loads the contents of filename as a JSON file."""
  with open(filename) as json_file:
    data = json.load(json_file)
  return data


def format_car(car):
  """Given a car dictionary, returns a nicely formatted name."""
  return "{} {} ({})".format(
      car["car_make"], car["car_model"], car["car_year"])


def process_data(data):
  """Analyzes the data, looking for maximums.

  Returns a list of lines that summarize the information.
  """
  max_revenue = {"revenue": 0}
  max_sales = {"total_sales": 0}
  most_popular = {"car_year": 0, "total_sales_in_that_year": 0}
  # dict_popular:: key=>year, value=>total_sales
  dict_popular = {}
  for item in data:
    # Calculate the revenue generated by this model (price * total_sales)
    # We need to convert the price from "$1234.56" to 1234.56
    item_price = locale.atof(item["price"].strip("$"))
    item_revenue = item["total_sales"] * item_price
    if item_revenue > max_revenue["revenue"]:
      item["revenue"] = item_revenue
      max_revenue = item
    # TODO: also handle max sales
    if item["total_sales"] > max_sales["total_sales"]:
      max_sales = item
    # TODO: also handle most popular car_year
    if item["car"]["car_year"] in dict_popular.keys():
      dict_popular[item["car"]["car_year"]] += int(item["total_sales"])
    else:
      dict_popular[item["car"]["car_year"]] = int(item["total_sales"])
        
  for key in dict_popular.keys():
    if dict_popular[key] > most_popular["total_sales_in_that_year"]:
      most_popular["car_year"] = key
      most_popular["total_sales_in_that_year"] = dict_popular[key]


  summary = [
    "The {} generated the most revenue: ${}".format(format_car(max_revenue["car"]), max_revenue["revenue"]),
    "The {} had the most sales: {}".format(max_sales["car"]["car_model"], max_sales["total_sales"]),
    "The most popular year was {} with {} sales.".format(most_popular["car_year"], most_popular["total_sales_in_that_year"])      
  ]

  return summary


def cars_dict_to_table(car_data):
  """Turns the data in car_data into a list of lists."""
  table_data = [["ID", "Car", "Price", "Total Sales"]]
  for item in car_data:
    table_data.append([item["id"], format_car(item["car"]), item["price"], item["total_sales"]])
  return table_data


def main(argv):
  """Process the JSON data and generate a full report out of it."""
  data = load_data("{}/car_sales.json".format(path))
  summary = process_data(data)
  
  # TODO: turn this into a PDF report
  table_data = cars_dict_to_table(data)
  report = SimpleDocTemplate(pdf_path)
  body_content = summary[0] + "<br/>" + summary[1] + "<br/>" + summary[2]
  report_summary = Paragraph(body_content)
  report_table = Table(data=table_data)
  report.build([report_summary, report_table])
  # TODO: send the PDF report as an email attachment
  sender = "automation@example.com"
  receiver = "{}@example.com".format(os.environ.get('USER'))
  subject = "Sales summary for last month"
  body = body_content.replace("<br/>", "\n")

  message = emails.generate(sender, receiver, subject, body, pdf_path)
  emails.send(message)

if __name__ == "__main__":
  main(sys.argv)
